### ISSUE TITLE
Search for videos on Tools> Upload files

### ISSUE THREAD

**Issue by DavelBM** [DavelBM/ProductionEnvironment#1]
http://teamvip.ca/node/add/attachment

![screen shot 2018-05-15 at 10 25 00](https://user-images.githubusercontent.com/31047486/40073018-82bca37e-582a-11e8-95f3-df96e5f24042.png)

**Comment by mastorgal** [comment]
Couldnt replicate this issue @DavelBM

**Comment by DavelBM** [comment]
@mastorgal Try and search for something, even just typing two characters and clicking elsewhere brings that error.

**Comment by alvidales** [comment]
@DavelBM This is fixed under development, I was not able to replicate the issue:
![image](https://user-images.githubusercontent.com/5848138/43354135-9096d2ae-9203-11e8-8671-91649982e1c0.png)
It works as expected on my end:
![image](https://user-images.githubusercontent.com/5848138/43354140-a2e055fc-9203-11e8-9315-a4c737f4037e.png)

**Comment by LuisCastrejon** [comment]
is solved, the problem is not replicated. the ajax error caused was presented only on that occasion
