### ISSUE TITLE
Welcome team name

### ISSUE THREAD

**Issue by DavelBM** [DavelBM/ProductionEnvironment#11]
- [x] We're pulling this from here,  was it just a placeholder or Lorand saved that entry?  

- [x] Also, overflow if long name - increase the width or break line on word not on a letter

![screen shot 2018-05-15 at 11 50 46](https://user-images.githubusercontent.com/31047486/40077357-4acc4760-5836-11e8-9a12-a98a6c472b63.png)

-----

![screen shot 2018-05-15 at 11 48 01](https://user-images.githubusercontent.com/31047486/40077355-4903d132-5836-11e8-97bc-05dbd438fbb6.png)

**Comment by mastorgal** [comment]
> We're pulling this from here, was it just a placeholder or Lorand saved that entry?

Lorand saved that entry, if you remove the text without saving the form you can see the placeholder

> Also, overflow if long name - increase the width or break line on word not on a letter
I have changed the attribute from break-all to break-word, it makes the complete word Name! to break line

If you have time check it and let me know if you want me to add a text-align: center;

**Comment by DavelBM** [comment]
Ok so this should perform a line breake not on the letter but the entire word... play around w the clear attribute on css ;)
