### ISSUE TITLE
Browse Channels

### ISSUE THREAD

**Issue by LuisCastrejon** [DavelBM/ProductionEnvironment#29]
All videos in Browse Channels the options do not adapt to the width of the box

![browse-channels](https://user-images.githubusercontent.com/40001633/41255223-0ee78126-6d83-11e8-9dab-a74f10c8829c.png)

Platforms: En Mac OSX 10.13, IPAD PRO, IPAD Air 2

**Comment by mastorgal** [comment]
This is not a bug, it is designed as specified in the UI designs.
