### ISSUE TITLE
Image constrained > upload videos

### ISSUE THREAD

**Issue by DavelBM** [DavelBM/ProductionEnvironment#3]
<img width="295" alt="What we have now" src="https://user-images.githubusercontent.com/31047486/40073446-b64a3566-582b-11e8-9f2b-5d7ceac8409b.png">

**A better approach:**

<img width="295" alt="Better approach, preview not available" src="https://user-images.githubusercontent.com/31047486/40075117-50db410c-5830-11e8-8528-72a8570bf2d8.png">

**Comment by mastorgal** [comment]
Fixed on theming

**Comment by DavelBM** [comment]
@mastorgal let’s do a push to production
