### ISSUE TITLE
User List

### ISSUE THREAD

**Issue by Visilink** [DavelBM/ProductionEnvironment#39]
As a site_admin, we'd like all site admin users to be able to generate a list of users defined on the system, and their access rights.

Current option is to "create" a user or "find an user" (should be "Find a User")... but unless you know the user's ID, you won't be able to find them. Ideally, the search would be on the user's first or last name, in addition to username/ID. 

But a full list of all users is essential

**Comment by DavelBM** [comment]
1. search based on name or email is extremely important!

2. Fix the typo. it should say <b>"Find a User"</b>
