### ISSUE TITLE
Live Broadcast Instructions

### ISSUE THREAD

**Issue by mastorgal** [DavelBM/ProductionEnvironment#41]
There is a new section in Live page where the user can get the parameters to stream using a 3rd party software like OBS

![start stream admin](https://user-images.githubusercontent.com/39312222/41482086-a0125be2-7091-11e8-82ef-4035e391d668.png)
![start stream admin copy](https://user-images.githubusercontent.com/39312222/41482089-a2786ce6-7091-11e8-9127-afe333d43d29.png)

**Comment by DavelBM** [comment]
I thought we already implemented this, is it ready yet or not?

**Comment by alvidales** [comment]
This is implemented, the parameters can be changed anytime, but the instructions need to be written in order for this to be complete.

**Comment by alvidales** [comment]
OBS is the default and free tool for the clients to stream out, but other tools can be implemented, instructions for OBS will be deployed in the proper section.

**Comment by alvidales** [comment]
RAW Documentation can be seen in the following link, already passed it to the developers to integrate on the site.
https://www.evernote.com/l/AQZHiiULUjlBa63GIurZOZ4MA2N4-gI9Xs4
