### ISSUE TITLE
Live player built-in buttons are broken in MAC

### ISSUE THREAD

**Issue by mastorgal** [DavelBM/ProductionEnvironment#42]
Start broadcasting button still broken in Live player, probably it might be the same for Join Stream button

**Comment by alvidales** [comment]
@mastorgal what are the specifics for this issue, In Mac I see the following:
Chrome
![image](https://user-images.githubusercontent.com/5848138/42788496-05a02efa-891d-11e8-9495-dd8c3938224c.png)
Safari (Before that image it appears as Chrome for a moment)
![image](https://user-images.githubusercontent.com/5848138/42788623-db2a6072-891d-11e8-94e0-4703a2ac938a.png)
Firefox
![image](https://user-images.githubusercontent.com/5848138/42788705-48ad4434-891e-11e8-802d-e0f51cec3303.png)

**Comment by alvidales** [comment]
@mastorgal Please give out some feedback and/or close the issue, thanks.

**Comment by mastorgal** [comment]
The main purpose of this issue was the styling of the Start broadcasting button, the text was longer than the button and the right side margin was not correctly.
