### ISSUE TITLE
Password Reset

### ISSUE THREAD

**Issue by Visilink** [DavelBM/ProductionEnvironment#47]
When you forget your password, you can reset it with the reset link.

I get an email with a one-time use link, and it does log you in.

The use is sent to the home page (logged in)... but then unless the user is encouraged to change their password, they still won't know what it is for next time.

Therefore, it would make sense that the following happens right after the use the "reset password link":
- the user should be sent to a page where they can specify the new password
- the new password should be specified twice to prevent mistakes in entry
- when you click "Save Password", a message should appear on the screen indicating that it was successfully modified

The above would make it more obvious to the user how to change the password.

Thanks
Lorand

https://www.dropbox.com/s/a7knb707zps1qm8/2018-06-16_9-19-28.jpg?dl=0

**Comment by DavelBM** [comment]
Basically, the reset password is not working as it should guys! Please check @Visilink comments!

**Comment by alvidales** [comment]
@mastorgal Please add SMTP module to send emails under theming, will send credentials to set it up.
