### ISSUE TITLE
Background Color on Visilink Logo

### ISSUE THREAD

**Issue by Visilink** [DavelBM/ProductionEnvironment#48]
Hi,
I'd like to be able to change the color behind the Visilink logo, or if that isn't possible, I need some options.

One option would be for me to be able to upload an image that has a background color. We would like it to be solid black or solid white. 

https://www.dropbox.com/s/3rbb7fztut8vork/2018-06-16_9-30-03.jpg?dl=0

Thanks,
Lorand

**Comment by Visilink** [comment]
![2018-06-30_9-19-43](https://user-images.githubusercontent.com/39421656/42126493-da9af538-7c46-11e8-81b5-e1f00a00a457.jpg)

**Comment by DavelBM** [comment]
we can add more shadow to the SVG. let's try that and see how it shows...
