### ISSUE TITLE
Download button open in a new tab

### ISSUE THREAD

**Issue by LuisCastrejon** [DavelBM/ProductionEnvironment#49]
Attachments the download button opens the file in a new tab

![button](https://user-images.githubusercontent.com/40001633/41747508-7a30783a-756b-11e8-964d-1657728f57a2.png)

**Comment by DavelBM** [comment]
that's ok... if you are in chrome. what would you like to see instead?

**Comment by LuisCastrejon** [comment]
I think the ideal would be to start the download directly
