### ISSUE TITLE
User Management

### ISSUE THREAD

**Issue by Visilink** [DavelBM/ProductionEnvironment#57]
- need to be able to search for users
- the current search does not return any results
- need to be able to search for a user by username, first name, last name, email address
- many of our clients have 100's of users. Therefore, I'd like to see a sort capability, and how pagination will look like when the user list doesn't fit on one page

**Comment by Visilink** [comment]
![2018-06-30_9-13-00](https://user-images.githubusercontent.com/39421656/42126531-8815e1a0-7c47-11e8-963c-8a9ad73eae82.jpg)

**Comment by DavelBM** [comment]
this is a duplicate of issue #58
