### ISSUE TITLE
File Upload - Sequence

### ISSUE THREAD

**Issue by Visilink** [DavelBM/ProductionEnvironment#59]
The process of uploading large video files can be very time consuming. 

Is there a way to warn the user ahead of time of this process? Here I started to upload a short video, and you'll notice I have to wait 15 minutes just for one video. I'm on a very high speed connection, with over 10 mbps uplink... so I'm thinking the upload speed must be a server side bottle-neck?

It would be helpful to have options explained to the user during the admin process.

Thoughts?
Thanks
Lorand

**Comment by Visilink** [comment]
![2018-06-30_9-37-51](https://user-images.githubusercontent.com/39421656/42126751-f5f55b72-7c49-11e8-84ef-ef1fd7567d3b.jpg)

**Comment by DavelBM** [comment]
this will be fixed with the implementation of the new transcoder and the new cdn.
