### ISSUE TITLE
Accuracy of Upload times

### ISSUE THREAD

**Issue by Visilink** [DavelBM/ProductionEnvironment#60]
Uploading is giving times that are not accurate.

I started an upload about 40 minutes ago... the file size is 600 MB. The time indicated to upload was about 15 minutes.

Now, after 40 minutes, the time is still indicating about 12-13 minutes. Progress bar is showing progress. But I;m  tied to this screen without being able to work on other admin functions.

This user experience will not be acceptable to our clients. We will need alternatives methods and accurate communications of progress.

Thanks
Lorand

**Comment by Visilink** [comment]
![2018-06-30_10-21-08](https://user-images.githubusercontent.com/39421656/42127103-04c4be44-7c50-11e8-84aa-0aed6c45cb9b.jpg)

**Comment by DavelBM** [comment]
Should be Fixed w new transcoder.
