### ISSUE TITLE
Video Upload - not attaching

### ISSUE THREAD

**Issue by Visilink** [DavelBM/ProductionEnvironment#61]
I uploaded a video, and got a message asking if I want to attach it to an existing video. There is no option to say "no". Hence I run the risk of loosing my upload.

In the end, I attached to a video that I randomly found, but I didn't want to do this.

The process is very unclear.

**Comment by Visilink** [comment]
![2018-06-30_11-02-25](https://user-images.githubusercontent.com/39421656/42127419-863108f2-7c55-11e8-8d4f-1de6bd5da269.jpg)

**Comment by mastorgal** [comment]
We have removed the required option from the field "Attach to a video?"

Changed in:
theming
staging
demo
teamvip
