### ISSUE TITLE
Add thumbnail to carrousel item

### ISSUE THREAD

**Issue by LuisCastrejon** [DavelBM/ProductionEnvironment#63]
Add Image when a video does not have Thumbnail

![thumbnail](https://user-images.githubusercontent.com/40001633/42911632-13ab4b00-8aa9-11e8-9e3c-34bc27ef10be.jpg)

**Comment by DavelBM** [comment]
By now we should've already figured out how to pull one of the 1st frames of the video, and if the video hasn't processed yet then show "still processing" instead of no image at all.

**Comment by alvidales** [comment]
We will add a default preview image for when the thumbnail is not rendered yet. @mastorgal please review this and comment, we can upload a default image and place it in the else statements for when no thumbnail exists.
